Create 20170912-prediction-of-huawei-sales-of-vidhance-models.md
imintinvestors/imintinvestors.com pull request #1
Opened 2017-09-12 13:24 UTC by vvizard-

Proposed article about Huawei sales predictions

2017-09-12 22:35 UTC, simonmika reviewed
Good in general. Maybe it might be worth splitting it into one piece talking about which models contain Vidhance and another about the potential volumes. The second can reference the first. Just a suggestion. Great work by the way.

2017-09-12 22:35 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +# Prediction of Huawei sales of Vidhance models
You don't have to give the title as an header. It is added automatically. This also means that you can reduce header levels by one in the rest of the document.

2017-09-12 22:35 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +## Disclaimer
I suggest calling it _Background_ instead. It sounds a little less boring.

2017-09-12 22:35 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +The Mate 9 family includes the "Mate 9", "Mate 9 Pro" and "Mate 9 Porsche design". The "Mate 9 Lite" is not included, as it does not run Vidhance software. The Mate 9 Family was announced in October
Maybe state very early in the article that Lite are totally different models and then define the Mate 9 Series and use that everywhere.

2017-09-12 22:35 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +___Huaweis previous flagship record is held by the P9 which sold 12 million units within it's first 11 months. The only datapoint we got for P10 so far, shows it's selling 36% better than the P9 did
Second last word should be "hasn't".

2017-09-12 22:35 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +This is tough. Detailed sales about any Honor model are hard to come by. We know that yearly sales of the Honor subsidiary accounted for approximately 60 million units of Huawei's total 139.3 shipped
"while the Honor 9 (with Vidhance) _has_ exceeed"

2017-09-12 22:35 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +__Based on strong year-on-year growth for the Honor brand, and the "Honor 9" realtively cheap chinese price, compared to the P10, one could expect this to sell a lot of units. But it got a lot of com
Try only to highlight a few words at a time. These long paragraphs are not suitable to skim through. Instead try to find the few words in every part that actually highlights the conclusion.

2017-09-12 23:00 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +___Based on similarity with P9 in sales volumes so far, the fact that Mate-series is usually outsold by the P-series, but accounting for that 2017 so far have shown a 20.6% unit shipment increase fro
Use single underscore.

2017-09-12 23:00 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +___Huaweis previous flagship record is held by the P9 which sold 12 million units within it's first 11 months. The only datapoint we got for P10 so far, shows it's selling 36% better than the P9 did
Single underscore again.

2017-09-12 23:00 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +> __I expect these three models to combined sell between 33 to 38 million units during their first 12 months__.
Don't use underscore for the full quote. And make the quote as self explanatory as possible while still being short enough for Twitter.

2017-09-12 23:00 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +> __I expect these three models to combined sell between 33 to 38 million units during their first 12 months__.
And move it higher up in the document (just a few lines) and leave a version of it here as well.

2017-09-12 23:11 UTC, simonmika requested changes
I will have to update the css to handle the images.

2017-09-12 23:11 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +> _"By the third quarter of 2016, 60% of Huawei’s smartphone shipments were mid- and high-priced devices, a striking reversal of its past reliance on cheap handsets."_
Don't add quote signs when using `>` as they will be added by the css. Also remember that quotes a flown outside of the regular text so you might too have a shorter version in the quote and a longer version left here. Also don't emphasize full sentences.

2017-09-12 23:11 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +|Name| Running Vidhance stabilization?|
You need another newline before the table for it too work.

2017-09-12 23:11 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +Both the Mate 9 and the P10 comes in several variants. The variants are
End line with `:`.

2017-09-12 23:11 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +| Model | Released | Month 1 | Month 2 | Month 3  | Month 4  | Month 5  | Month 6  | Month 7  | Month 8  | Month 9  | Month 10  | Month 11  | Month 12|
This table is too wide for the page. I might find a way to fix it but we should consider rearranging the data somehow.

2017-09-12 23:11 UTC, simonmika commented on content/article/20170912-prediction-of-huawei-sales-of-vidhance-models.md
> +---
This line makes no sense as the links below actually will show up at their usage.

2017-09-14 12:14 UTC, vvizard- commented
Regarding CSS and images. What was the problem? Is it something you will update, or should I make changes? If so, what?

2017-09-14 17:20 UTC, simonmika commented
I already fixed the images.

2017-09-15 14:45 UTC, simonmika approved these changes

2017-09-15 14:45 UTC, merged